### ISSUE TITLE
Incorrect call in SimpleCacheTest::testSetMultiple

### ISSUE THREAD

**Issue by weierophinney** [php-cache/integration-tests#92]
Within `SimpleCacheTest::testSetMultiple()`, the test makes the following call:

```php
$result = $this->cache->setMultiple(['0' => 'value0']);
```

and later:

```php
$this->assertEquals('value0', $this->cache->get('0'));
```

I assert that the original `setMultiple` call should fail. PHP silently converts string array keys that contain integers to integers; thus, `'0'` will become `0`, which PSR-16 would consider an invalid key. (See [this example on 3v4l for confirmation](https://3v4l.org/TODgK).)

The test should use valid string keys:

```php
$result = $this->cache->setMultiple(['key0' => 'value0']);
// ...
$this->assertEquals('value0', $this->cache->get('key0'));
```

**Comment by prisis** [comment]
Do you have some time to make a pr?

**Comment by jasny** [comment]
### I strongly oppose to this

`'0'` is a valid key. The fact PHP transforms a key string into an integer is a language detail. That `setMultiple` requires an associated array is unfortunate.

`setMultiple` is an important method to increase performance. We some valid keys unavaible to be used by `setMultiple` because of a PHP language quirk.

Example, if someone is doing

```php
foreach ($items as $item) {
  $cache->set((string)$item->reference, $item);
}
```

one might advise him to optimize this as

```php
$values = [];
foreach ($items as $item) {
  $values[(string)$item->reference] = $item;
}
$cache->setMultiple($values);
```

Given that `reference` can be any alphanumeric string, this change would **unexpectedly break** his code if any item had a (valid) numeric key.

**Comment by kodeart** [comment]
+1 because the current PHP (5 and 7) internally converts the stringed integers to integers and THIS is unfortunate. IMHO the proposed PSR (and any implementation) should be validated with specific integration suite **built on the current language** quirks/features/details. If the PHP internals change this behavior, so the tests should change -- as in the latest case of internal typecast of floats-to-strings. This array drama is a PHP trademark, unfortunately.

**Comment by nicolas-grekas** [comment]
That's an issue with the implementation, not with the test suite. Not all implemens have the issue btw. Broken ones should be fixed, not the test suite.

**Comment by MGatner** [comment]
I don't understand how this is not a test issue. The moment `['0' => 'value0']` is declared the key is an integer. Kint cannot distinguish:
```
┌───────────────────────────────────────────────────────────────────────┐
│ $array                                                                │
└───────────────────────────────────────────────────────────────────────┘
array (1) [
    0 => string (6) "value0"
]
┌───────────────────────────────────────────────────────────────────────┐
│ array_keys(...)                                                       │
└───────────────────────────────────────────────────────────────────────┘
array (1) [
    0 => integer 0
]
══════════════════════════════════════════════════════════════════════════
Called from <ROOT>/vendor/cache/integration-tests/src/SimpleCacheTest.php
```

Neither can PHPUnit:
```
$this->assertSame([0 => 'value0'], ['0' => 'value0']); // true
```

If this one very specific case needs to be acceptable then it means `setMultiple()` must treat all integer keys as strings and is unable to fail the way more blatant problem of passing in a non-associative array.
